### ISSUE TITLE
无通知

### ISSUE THREAD

**Issue by shzxm** [Hootrix/keyword_alert_bot#1]
已经正常安装
但无论监听什么关键字
均无反应
python 后端无报错
可以正常订阅.但是无法推送

##bot日志
şͨ ǫ̎ ņ̻ g̀͝ & s͓̮ ȏͅ n̴͉ g̶̤ 14:39 PM UTC+8 🕝, [27.07.20 14:35]
/subscribe 你好 https://t.me/songsongtest

subscription, [27.07.20 14:35]
success subscribe:
keyword:你好  channel:songsongtest

şͨ ǫ̎ ņ̻ g̀͝ & s͓̮ ȏͅ n̴͉ g̶̤ 14:39 PM UTC+8 🕝, [27.07.20 14:36]
/list

subscription, [27.07.20 14:36]
keyword: 你好
channel: https://t.me/songsongtest
---

şͨ ǫ̎ ņ̻ g̀͝ & s͓̮ ȏͅ n̴͉ g̶̤ 14:39 PM UTC+8 🕝, [27.07.20 14:36]
/subscribe 1 https://t.me/songsongtest

subscription, [27.07.20 14:36]
success subscribe:
keyword:1  channel:songsongtest

##python日志
[root@server keyword_alert_bot]# pipenv install --python 3.6.8
Creating a virtualenv for this project…
Pipfile: /root/keyword_alert_bot/Pipfile
Using /usr/bin/python3.6m (3.6.8) to create virtualenv…
⠼ Creating virtual environment...created virtual environment CPython3.6.8.final.0-64 in 186ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/keyword_alert_bot-rbc3Eq6Z, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.1.1, setuptools==49.2.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/keyword_alert_bot-rbc3Eq6Z
Warning: Your Pipfile requires python_version 3.7, but you are using 3.6.8 (/root/.local/share/v/k/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing dependencies from Pipfile.lock (ddc0e2)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 8/8 — 00:00:14
(keyword_alert_bot) [root@server keyword_alert_bot]# pipenv shell --python 3.6.8
Shell for /root/.local/share/virtualenvs/keyword_alert_bot-rbc3Eq6Z already activated.
No action taken to avoid nested environments.
(keyword_alert_bot) 
[root@server keyword_alert_bot]# python3 main.py 
1311943675 HostLoc新帖通知 160693 45.91.80.X    这个段谁有的联系
MJJ:k2p2
时间:2020-7-27
https://www.hostloc.com/thread-722871-1-1.html

**Comment by Hootrix** [comment]
嗯，我空了看下什么原因。我这里正常推送

**Comment by Hootrix** [comment]
有时候终端没有显示报错，用的框架原因。需要断点，或者手动print

**Comment by shzxm** [comment]
> 嗯，我空了看下什么原因。我这里正常推送

不知道能不能直接
用pip3 install 下列依赖?使用python3 直接运行
telethon =“ *”
pysocks =“ *”
peewee =“ *”
pyyaml =“ *”
diskcache =“ *”

**Comment by shzxm** [comment]
pipenv还是有点木乱.接触的比较少

**Comment by Hootrix** [comment]
requirements.txt
```
certifi==2020.6.20
chardet==3.0.4
diskcache==4.1.0
idna==2.10
peewee==3.13.3
pyaes==1.6.1
pyasn1==0.4.8
PySocks==1.7.1
PyYAML==5.3.1
rsa==4.6
Telethon==1.15.0
urllib3==1.25.10
```

**Comment by Hootrix** [comment]
> pipenv还是有点木乱.接触的比较少

`pip3 install -r requirements.txt` 应该都一样，你试试

**Comment by shzxm** [comment]
> 
> 
> requirements.txt
> 
> ```
> 
> certifi==2020.6.20
> 
> chardet==3.0.4
> 
> diskcache==4.1.0
> 
> idna==2.10
> 
> peewee==3.13.3
> 
> pyaes==1.6.1
> 
> pyasn1==0.4.8
> 
> PySocks==1.7.1
> 
> PyYAML==5.3.1
> 
> rsa==4.6
> 
> Telethon==1.15.0
> 
> urllib3==1.25.10
> 
> ```

好嘞，我试一下

**Comment by shzxm** [comment]
> > pipenv还是有点木乱。接触的比较少
> 
> `pip3 install -r requirements.txt` 应该都一样，你试试

问题解决了.
希望能支持 Group
