### ISSUE TITLE
[BUG]Connection to Telegram failed 5 time(s)

### ISSUE THREAD

**Issue by hyperbolic-c** [Hootrix/keyword_alert_bot#104]
**问题描述 Describe the bug**
请简洁明了地描述您遇到的问题。A clear and concise description of what the bug is.
开启了代理在py文件中登录Telegram的时候还是连接失败。请问作者使用的是哪家的代理，有推荐吗，谢谢！
![image](https://github.com/user-attachments/assets/e9186dca-637f-4d3e-82ef-55480b7bf26d)

**Comment by Hootrix** [comment]
推荐直接使用境外服务器，其次才使用代理方式

**Comment by hyperbolic-c** [comment]
换了好多都不行，我用了Pyrogram库就能连上，好奇怪，Telethon不行。谢谢作者回复！
