### ISSUE TITLE
请问我重新搭建倒入db后无反应

### ISSUE THREAD

**Issue by fangpidedongsun** [Hootrix/keyword_alert_bot#107]
你好，由于最初搭建使用的新账号，导致没有定期活动账号被删除，现在重新使用docker搭建并更换了账号，倒入了以前的数据库。
程序运行没有问题，发送命令也有反馈，但是不监控原有关键词，新加入关键词也不监控。

另外，还有一个问题，像这种重新搭建倒入数据库后，机器人会自动轮训数据库吗？前提是新账号没有关注数据库内的频道。

**Comment by Hootrix** [comment]
可靠的办法是取消后重新订阅。
bot接管的账号必须要关注监听的频道。切换账号后导入DB是不会自动处理的
