### ISSUE TITLE
重复发送相同消息

### ISSUE THREAD

**Issue by double-tu** [Hootrix/keyword_alert_bot#11]
重复推送相同内容的消息

Find 链接: [https://t.me/hezu2/18135](https://t.me/hezu2/18135)

![重复消息](https://files.catbox.moe/135gpm.png)

**Comment by Hootrix** [comment]
![image](https://user-images.githubusercontent.com/10736915/154890640-4c04744a-9949-4af7-8fe6-f10e989e6aa2.png)

没复现。你的订阅id是多少我测试下
/list 查看

**Comment by Hootrix** [comment]
的确有出现。空了再看看😂
