### ISSUE TITLE
点击list没反应

### ISSUE THREAD

**Issue by fangpidedongsun** [Hootrix/keyword_alert_bot#13]
↑ **请将上方标题修改为 “头像墙加入归档”** ↑  

### 您的GitHub主页地址：
> https://github.com/{用户名}

**Comment by Hootrix** [comment]
没发现。 或许机器抽风了，最好方式是自己部署

**Comment by fangpidedongsun** [comment]
> 没发现。 或许机器抽风了，最好方式是自己部署

好吧，可是我现在无法导出list，不知道从后台可以导出给我吗

**Comment by Hootrix** [comment]
截图看看呢。 马上点了`/list` 命令后的界面

**Comment by fangpidedongsun** [comment]
> 截图看看呢。 马上点了`/list` 命令后的界面
![image](https://user-images.githubusercontent.com/55946288/159847941-50d54b6a-6ebb-42fb-96b9-5c51e0025921.png)
点了 没有反应

**Comment by Hootrix** [comment]
那是bug了。
先用机器人 @RawDataBot 获取chat id 
我帮你找回订阅数据

**Comment by Hootrix** [comment]
是订阅的太多，消息体文本超过了4096字符😂。要翻页才行

**Comment by Hootrix** [comment]
> 

可以再试试，或许修复好了

**Comment by fangpidedongsun** [comment]
> > 
> 
> 可以再试试，或许修复好了

好了好了，感谢
