### ISSUE TITLE
为什么不能手工验证解决加群验证的问题？

### ISSUE THREAD

**Issue by crazypeace** [Hootrix/keyword_alert_bot#14]
或者先手工操作加群的那个ID，把群加进去并通过加群验证。
然后让BOT接管加群的ID，开始侦测关键词。

**Comment by Hootrix** [comment]
不太明白。

目前所用加入验证群方式：
	
	1. 让管理员手动允许
	2. 自己登录监听消息的账号手动入群（需自己部署）
