### ISSUE TITLE
匹配多个关键字的消息，如何才能只发送一次？

### ISSUE THREAD

**Issue by crazypeace** [Hootrix/keyword_alert_bot#18]
作者你好！
我希望 匹配多个关键字的消息，只发送一次。
我在发送消息后面加了一个终止，但好像没有效果。
await bot.send_message(receiver, message_str,link_preview = True,parse_mode = 'markdown')
raise events.StopPropagation # 匹配消息只发送一次

**Comment by Hootrix** [comment]
暂不支持，需要添加判重逻辑

**Comment by crazypeace** [comment]
我读了一下代码，我以为在bot给订阅者发送消息之后把流程中断，就会开始判断下一条消息了。
（我的修改就如顶楼描述的那样）

请问我是哪里理解有问题？
是因为多线程吗？

**Comment by Hootrix** [comment]
不使用break方法：

在`except Exception`之前捕获StopPropagation异常且抛出

```python
except events.StopPropagation as _e:
  raise _e
```

**Comment by crazypeace** [comment]
> 但是这样做会导致只有一个订阅该频道的用户才能收到消息，因为订阅列表被强制退出了

恕我冒昧，提个想法供您参考。

我认为从程序设计的角度出发, 遍历订阅列表的行为应该设计为：
```
遍历用户
    遍历关键字
        如果关键字匹配，上报消息，中断遍历关键字
    下一个关键字
下一个用户
```

当然，如果希望将匹配的关键字都上报，但是消息只上报一次。可以这样：
```
遍历用户
    遍历关键字
        如果关键字匹配，记录匹配的关键字
    下一个关键字
    如果关键字匹配列表不为空，上报消息 + 关键字匹配列表
下一个用户
```

**Comment by Hootrix** [comment]
可以，有优化建议提交PR就行。 能让他更稳定运行就好😂

**Comment by crazypeace** [comment]
抱歉，我不知道怎么在pull request 的时候只pull一部分文件

line 119
# 配合后面5秒cache, 实现若一条消息匹配多个判断条件, 只发送一次
CACHE_MSG_UNIQUE_SEND = f'{receiver}_{message.id}'

line 153
if cache.add(CACHE_KEY_UNIQUE_SEND,1,expire=5) and cache.add(CACHE_MSG_UNIQUE_SEND,1,expire=5):

line 169
if cache.add(CACHE_KEY_UNIQUE_SEND,1,expire=5) and cache.add(CACHE_MSG_UNIQUE_SEND,1,expire=5):

**Comment by Hootrix** [comment]
```
# 默认按照订阅去重
CACHE_KEY_UNIQUE_SEND = f'{receiver}_{l_id}'

# 这应该是按照消息去重（若该消息同时命中多条订阅，将只返回第一条命中订阅）
CACHE_MSG_UNIQUE_SEND = f'{receiver}_{message.id}'
```


默认是第一种去重规则，后面增加config来解决吧。满足自定义需求

**Comment by crazypeace** [comment]
作者你好， 请问我是不是应该这样：
重新fork一份，然后只修改这三个地方，然后提 pull request?

**Comment by Hootrix** [comment]
config.yml添加配置：

```yml
msg_unique_rule: MESSAGE_ID 
```
参考位置：
https://github.com/Hootrix/keyword_alert_bot/blob/master/config.yml.default#L34
