### ISSUE TITLE
Add multiple, show this, how to solve?

### ISSUE THREAD

**Issue by 635783796** [Hootrix/keyword_alert_bot#19]
无法使用该频道：pionexcn

Channel error, unable to use: You have joined too many channels/supergroups (caused by JoinChannelRequest)

**Comment by 635783796** [comment]
有些频道无法使用吗？

**Comment by Hootrix** [comment]
加入的频道/群组超过数量限制

https://webapps.stackexchange.com/questions/125006/what-are-the-limits-for-channels-and-supergroups#answer-125075

**Comment by Funkmayer** [comment]
Sorry, same issue here, trying to subscribe at least 1 channel for 1 keyword i receive the same response of the friend above:

Channel error, unable to use: You have joined too many channels/supergroups (caused by JoinChannelRequest)

any suggest please?

thanks!

**Comment by 635783796** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hootrix** [comment]
merge to:
