### ISSUE TITLE
Where should I Put in my Bot ID and API ?

### ISSUE THREAD

**Issue by koke96** [Hootrix/keyword_alert_bot#2]
Hey that's a nice working bot there and it is working exactly the way it should but I need to create multiple copies of that bot so I am trying to replicate your code but the code is too complex for me. Help would be appreciated .

Regards,
Kaustubh

**Comment by Hootrix** [comment]
`config.yml`

**Comment by Hootrix** [comment]
> `config.yml`

Refer to the information in the config.yml file.
Configuring your Telegram account and bot token

Telegram account for listening to messages.
bot token for sending
