### ISSUE TITLE
你好，你的演示机器人好像用不了哦，

### ISSUE THREAD

**Issue by 635783796** [Hootrix/keyword_alert_bot#20]
![image](https://user-images.githubusercontent.com/70841795/171366239-8a08071a-735a-4a65-865d-12324f01cfe9.png)
如上图，我添加了几个关键词，其中一个是下载，
![image](https://user-images.githubusercontent.com/70841795/171366378-8da0daf4-88bc-4581-9d92-7ca1a5d38f07.png)
我发了“下载”这个关键词到目标群，机器人没任何反应，大佬这个能解决么？

![image](https://user-images.githubusercontent.com/70841795/171366872-f5ef7115-1839-4106-85c5-50be14ebcf7d.png)

电报群链接：https://t.me/BinanceChinese

**Comment by Hootrix** [comment]
![image](https://user-images.githubusercontent.com/10736915/171513282-d0851439-5966-4386-912c-9a840cd8b786.jpeg)

这种群组有加群验证，机器人没有绕过方案

**Comment by 635783796** [comment]
> 解决方法：
> 
> 1. 联系团队管理员人工通过
> 2. 让我验证（长时间没空）
> 
> 验证通过后，不得随意退订（系统当前会退出没有用户的频道）

请问怎么联系团队管理员，有没有联系方式，或者你本人微信可以加一个么，交流学习一下，

**Comment by crazypeace** [comment]
> > 解决方法：
> > 
> > 1. 联系团队管理员人工通过
> > 2. 让我验证（长时间没空）
> > 
> > 验证通过后，不得随意退订（系统当前会退出没有用户的频道）
> 
> 请问怎么联系团队管理员，有没有联系方式，或者你本人微信可以加一个么，交流学习一下，

你可以自己搭这个机器人的，作者已经写了怎么自己搭的方法了。

**Comment by 635783796** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 635783796** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
