### ISSUE TITLE
ConnectionError: Connection to Telegram failed 5 time(s)

### ISSUE THREAD

**Issue by crazypeace** [Hootrix/keyword_alert_bot#22]
请问这种出错原因是什么？

日志：
Attempt 4 at connecting failed: OSError: [Errno 113] Connect call failed ('91.108.56.134', 443)
Attempt 4 at connecting failed: OSError: [Errno 113] Connect call failed ('91.108.56.134', 443)
Attempt 5 at connecting failed: OSError: [Errno 113] Connect call failed ('91.108.56.134', 443)
Attempt 5 at connecting failed: OSError: [Errno 113] Connect call failed ('91.108.56.134', 443)
Attempt 6 at connecting failed: OSError: [Errno 113] Connect call failed ('91.108.56.134', 443)
Attempt 6 at connecting failed: OSError: [Errno 113] Connect call failed ('91.108.56.134', 443)
Automatic reconnection failed 5 time(s)
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection to Telegram failed 5 time(s)')>
ConnectionError: Connection to Telegram failed 5 time(s)
Automatic reconnection failed 5 time(s)
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection to Telegram failed 5 time(s)')>
ConnectionError: Connection to Telegram failed 5 time(s)
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 468, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/etc/keyword_alert_bot-master/main.py", line 751, in <module>
    client.run_until_disconnected()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 84, in run_until_disconnected
    return self.loop.run_until_complete(self._run_until_disconnected())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 29, in _run_until_disconnected
    return await self.disconnected
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by crazypeace** [comment]
root@PR920627:/etc/keyword_alert_bot-master# tcptraceroute 91.108.56.134 443
Selected device eth0, address 204.44.83.99, port 43223 for outgoing packets
Tracing the path to 91.108.56.134 on TCP port 443 (https), 30 hops max
 1  66.154.107.1  0.818 ms  0.755 ms  0.723 ms
 2  96.44.175.32.static.quadranet.com (96.44.175.32)  9.516 ms  0.718 ms  0.854 ms
 3  sg.gs-pte.as24482.any2ix.coresite.com (206.72.211.16)  0.930 ms  0.940 ms  1.030 ms
 4  pisg-sggs1-246-128.sggs.sg (103.14.246.128)  170.133 ms  170.054 ms  173.234 ms
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  91.108.56.134 [open]  176.730 ms  176.671 ms  176.715 ms
root@PR920627:/etc/keyword_alert_bot-master#

**Comment by Hootrix** [comment]
看样子是网络问题。 proxy配置试试

**Comment by crazypeace** [comment]
谢谢作者回复。
我重启了一下，继续运行正常。
