### ISSUE TITLE
建议把channel title和 FOUND 写在一行 节约纵向空间

### ISSUE THREAD

**Issue by crazypeace** [Hootrix/keyword_alert_bot#29]
建议把channel title和 FOUND 写在一行 节约纵向空间
![image](https://user-images.githubusercontent.com/665889/178159272-3b55933f-da01-4e66-935b-7fb3bb49a0cb.png)

可以说是个人偏好。

**Comment by Hootrix** [comment]
空了试试。如果订阅关键字很多 或者频道名称超长了不知道显示效果咋样

**Comment by crazypeace** [comment]
> 

1. 这里只显示命中的关键字
2. 频道名字长就自动转弯了，从纵向高度来看肯定是变矮的（比你之前的中间空一行）
![微信图片_20220712115950](https://user-images.githubusercontent.com/665889/178405920-4d17672a-c4ab-4e9a-8b8c-e300be63c2e0.jpg)
