### ISSUE TITLE
关于bot无法转发消息的疑问

### ISSUE THREAD

**Issue by seyrenhe** [Hootrix/keyword_alert_bot#3]
是不是因为由client获取到的message，没办法通过bot 转发？有没有其他办法转发呢，因为发链接的话还需要点进去，而且通知里面也不会显示title。感觉有点不方便

**Comment by Hootrix** [comment]
> 是不是因为由client获取到的message，没办法通过bot 转发？有没有其他办法转发呢，因为发链接的话还需要点进去，而且通知里面也不会显示title。感觉有点不方便

尝试转发失败就寻找了替代方案，新发送message的话自定义性更强一些。

**Comment by Hootrix** [comment]
> > 是不是因为由client获取到的message，没办法通过bot 转发？有没有其他办法转发呢，因为发链接的话还需要点进去，而且通知里面也不会显示title。感觉有点不方便
> 
> 尝试转发失败就寻找了替代方案，新发送message的话自定义性更强一些。

估计是bot不支持消息的转发。我更希望是能解决的😂
如果需要发送原消息，可以把内容原样读取出来以新消息来发送，链接都可以不放进去；
至于通知栏标题的话，个人使用上感觉没有什么影响。

**Comment by seyrenhe** [comment]
谢谢作者的耐心答复，我试试构建新消息吧
