### ISSUE TITLE
添加群组的名称 (caused by ResolveUsernameRequest) 的问题

### ISSUE THREAD

**Issue by crazypeace** [Hootrix/keyword_alert_bot#34]
我的使用经验是，直接去查 数字ID

https://zelikk.blogspot.com/2022/03/telegram-bot-ResolveUsernameRequest-channel-id.html

**Comment by Hootrix** [comment]
![image](https://user-images.githubusercontent.com/10736915/179446465-df7309fe-ad5c-44cd-8619-516bad76deae.png)

**Comment by Hootrix** [comment]
为啥我这里看不到id

**Comment by Hootrix** [comment]
JoinChannelRequest支持传入频道id的话，那可以的 节省了一次接口请求

**Comment by crazypeace** [comment]
> 为啥我这里看不到id
我不知道为什么你看不到。
![image](https://user-images.githubusercontent.com/665889/179470961-94a26e3f-bad5-4709-8010-e66d071b19c2.png)

**Comment by crazypeace** [comment]
知道了，你换z版的web telegram去看id
ttps://web.telegram.org/z/
