### ISSUE TITLE
一直顯示「无法使用该频道」

### ISSUE THREAD

**Issue by RachelJian** [Hootrix/keyword_alert_bot#49]
輸入  /subscribe   免费     https://t.me/tianfutong  這指令可以成功訂閱
但輸入其他頻道都會顯示「无法使用该频道」Channel error, unable to use: You have joined too many channels/supergroups (caused by JoinChannelRequest)

**Comment by Hootrix** [comment]
加入的群组/频道数量超过了限制。我先手动清理下吧

max：500

**Comment by qtcwt** [comment]
我也遇到了同样的问题。求解决，万分感激！

**Comment by Simonwzm** [comment]
遇到了同样的问题，希望能够解决，感谢！

**Comment by Hootrix** [comment]
退订操作不会及时触发退群/频道。有消息后检测到无任何订阅后才会执行。

目前还没时间研究多账号部署监听，只有临时清理test😅

**Comment by Miao-WANG-Trista** [comment]
遇到了同样的问题

**Comment by Hootrix** [comment]
merged into #85
