### ISSUE TITLE
发送任何指令都是无回复

### ISSUE THREAD

**Issue by css561** [Hootrix/keyword_alert_bot#50]
![IMG_20230406_115402](https://user-images.githubusercontent.com/42743044/230268428-8d1bfc53-0bad-49ae-b47f-467031cf2e1e.jpg)
不管是：
/start
/subscribe
/unsubscribe_all
/subscribe
甚至/help
也都没有任何反应.....

**Comment by Hootrix** [comment]
服务器网络出现了问题。今晚迁移下

**Comment by Hootrix** [comment]
网络已恢复。暂时没做迁移😅
