### ISSUE TITLE
以正则表达式模式检测关键词不奏效

### ISSUE THREAD

**Issue by Defenesesword** [Hootrix/keyword_alert_bot#51]
使用README.md给出的regex关键词用例：
/subscribe  /([\S]{2}券)/g  https://t.me/example_channel
在受监测的channel中，有诸如“xxxx优惠券xxx”的信息出现时，bot不会给出FOUND的提示。
当然，普通的关键词监测是可以奏效（有FOUND消息输出）的。

**Comment by Hootrix** [comment]
自测通过
<img width="178" alt="image" src="https://user-images.githubusercontent.com/10736915/231479883-d1e3b1f1-b9f0-4a30-bd66-491dea968ae0.png">
message：123 xxxx优惠券xxx
<img width="192" alt="image" src="https://user-images.githubusercontent.com/10736915/231480036-2e7f4804-e0cb-43f5-9bd7-48a97b02d28d.png">


regex: /([\S]{2}券)/g
channel url: https://t.me/example_channel

**Comment by Hootrix** [comment]
最好提供下原始消息内容，方便测试

**Comment by Defenesesword** [comment]
是在自建的频道里发送和您这个一样的测试消息，依旧没有消息输出。
bot搭建在Ubuntu 18.04 LTS arm64 服务器上（一台魅族的魅蓝note mt6735 ：p）。服务器Python版本是3.6，没有按照您在README里的介绍用pipenv搭建。
也许是我这边的问题，稍后我换我自己的win10pc机试试看吧

**Comment by Defenesesword** [comment]
如果您需要测试我的bot的话，这是我搭建的bot：https://t.me/defsw0rd_kwbot

**Comment by Hootrix** [comment]
> 如果您需要测试我的bot的话，这是我搭建的bot：https://t.me/defsw0rd_kwbot

猜测是兼容性问题

可以找下日志，里面应该有报错

**Comment by Hootrix** [comment]
我用defsw0rd_kwbot监听，的确没收到正则的消息

**Comment by Defenesesword** [comment]
感谢您的提醒，问题已经得到解决，以下是解决方案，仅供参考（反正各位不要学我不更服务器python版本就是了）：

1. 按照@Hootrix的思路，在服务器上检查固定输出的keyword_alert.log:

   ```
   cat ./keyword_alert.log | grep <my_regex>
   ```

   没有什么有用的INFO输出...

2. 考虑到功能不能正常运行，也许属于ERROR级别了，在config.yaml里更改：

   ```
   # LOG
   logger:
     path: null # /root/absolute-path/   default null: _current_path
     #将level由INFO更改为ERROR
     level: ERROR # FATAL,ERROR,WARN,INFO,DEBUG,NOTSET
   
   ```

3. 再次检查keyword_alert.log，果然得到了有用信息：

   ```
   cat ./keyword_alert.log 
   >> ...ERROR:module 're' has no attribute 'Match'
   ```

4. 于是在main.py里定位到 line 235:

   ```
   if isinstance(regex_match,regex.Match):#search()结果
                   regex_match = [regex_match.group()]
   ```

5. 一开始我以为是re模块换名字成regex导致的原因，于是让re保持原名，同时把main.py里所有的regex换成了re：

   ```
   #import re as regex
   import re
   ```

   结果问题依旧，log里输出了和Step 3一样的ERROR。

6. 阅读代码上下文，提取js_to_py_re()函数和类型判断isinstance()，在我的服务器（Ubuntu 18.04 LTS arm64 with Python 3.6，No pipenv）和另一台主机（Windows 10 1809 with Python 3.10 and pipenv）造了个py做了测试：

   ```
   def js_to_py_re(rx):
   	...
   # 这里省略一万字。。。
   
   keywords = '/([\S]{2}券)/i'
   text = 'xxxx优惠券yyyy'
   re_match = js_to_py_re(keywords)(text)
   print(type(re_match))
   
   print(isinstance(re_match, re.Match))
   
   ```

   得到了截然不同的结果：

   ```
   # server（Ubuntu Python 3.6）
   
   <_sre.SRE_Match object; span=(4, 7), match='优惠券'>
   <class '_sre.SRE_Match'>
   Traceback (most recent call last):
     File "./transfer.py", line 40, in <module>
       print(isinstance(re_match, re.Match))
   AttributeError: module 're' has no attribute 'Match'
   
   # another device（Windows 10 Python 3.10 pipenv）
   
   <re.Match object; span=(4, 7), match='优惠券'>
   <class 're.Match'>
   True
   ```

   问题有了答案。

7. 可是<class '_sre.SRE_Match'>是什么鬼类型啊！

   我尝试把isinstance(re_match, re.Match)里的re.Match类型换成这个\_sre.SRE_Match，结果服务器的python直接提示说找不到这个_sre。
   
   最后没有办法，搞了个曲线救国，反正正则表达式不要求全文检索的时候，变量re_match类型肯定不是list嘛。
   
   ```
   # main.py line 235:
   if not isinstance(regex_match, list):#search()结果
                   regex_match = [regex_match.group()]
   ```
   
   再次运行机器人，问题得到解决。
   
   不建议其他人也这么搞，我毕竟是没有条件（不会更新python...），得自己创造条件上。
   
   再次感谢 @Hootrix 您的热心帮助！由于问题已经解决，我稍后会关闭该issue。
