### ISSUE TITLE
The bot doesn't work 

### ISSUE THREAD

**Issue by Saifulla14** [Hootrix/keyword_alert_bot#54]
↑ **请将上方标题修改为 “头像墙加入归档”** ↑  

### 您的GitHub主页地址：
> https://github.com/{用户名}
The bot works fine for few days, but spots working for 2-3 days and then restarts working. In the process i miss a lot of information from the channel that I'm using the bot for. Please help with this issue 🙏.

**Comment by Hootrix** [comment]
I haven't found any problems here temporarily. Are there subscribed channels and test keywords? Does this problem still exist now

**Comment by Saifulla14** [comment]
Yes the issue still persist.

**Comment by Hootrix** [comment]
Please provide subscription channels and keywords, I will test this question.

**Comment by Saifulla14** [comment]
Yeah sure,
/subscribe Available, available,booked,Booked https://t.me/F1_Visa_Slots_Only

**Comment by Hootrix** [comment]
Updated telethon dependency. To be observed👀

**Comment by Saifulla14** [comment]
It's working fine now. Thank you very much for your generous help 🙏.
