### ISSUE TITLE
[BUG] 基于较新的telethon库运行会产生concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by Defenesesword** [Hootrix/keyword_alert_bot#55]
**问题描述 Describe the bug**
（问题可能不易于复现）我为我的服务器更换了python3.7，但仍未按README要求使用pipenv。用pip安装完所有的库以后，运行一段时间并在telegram上向bot发送指令，bot会失效，不会返回任何信息，而且控制台会直接打印大量的错误（而不是打印至日志）：
...
concurrent.futures._base.CancelledError
经过查询资料了解到可能是telethon库的问题，查询到个人服务器端的telethon==1.28.5。而我在个人主机上用于测试的，可稳定运行带pipenv的telethon==1.24.0
我在服务器端更换了telethon为较旧的版本（依旧没有使用pipenv），问题便解决了，bot能稳定运行。
在README中有描述过更新telethon能够解决部分群组不能捕获消息的问题，我认为这个方案可能会导致新的（致命性的）bug，故提交该issue作为参考。

**订阅信息 command Info**
任意的指令，如/start，/list，/subscribe，/help等

**Comment by Hootrix** [comment]
不太清楚原因，目前我这运行正常🤔️

$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)


$ pip list 

Package     Version
----------- -------
asyncstdlib 3.10.6
diskcache   5.5.1
peewee      3.16.0
pip         22.3.1
pyaes       1.6.1
pyasn1      0.4.8
PySocks     1.7.1
PyYAML      6.0
rsa         4.9
setuptools  65.6.3
Telethon    1.28.5
wheel       0.38.4

**Comment by Hootrix** [comment]
我本地运行时使用socket代理有这个报错。切换到更稳定的网络环境后正常。
