### ISSUE TITLE
[BUG] JoinChannelRequest Error

### ISSUE THREAD

**Issue by pmpsn** [Hootrix/keyword_alert_bot#56]
Every time I try to use the bot, no matter the keyword or group link i get this error message:
"Channel error, unable to use: You have joined too many channels/supergroups (caused by JoinChannelRequest)"

**Comment by Hootrix** [comment]
telegram free account restrictions. Listening channels are limited to a maximum of 500

**Comment by tfanon** [comment]
Hi, I have the same issue. I have telegram premium and am only a member of 59 groups/channels. Is this norma?

**Comment by Hootrix** [comment]
> Hi, I have the same issue. I have telegram premium and am only a member of 59 groups/channels. Is this norma?

Does your own Telegram account being premium have nothing to do with this. This is related to the restricted account of the Telegram bot, which can monitor up to a maximum of 500 channels/groups. Unless the account is upgraded to extend it to 1000.

**Comment by zbroinx** [comment]
> > Hi, I have the same issue. I have telegram premium and am only a member of 59 groups/channels. Is this norma?
> 
> Does your own Telegram account being premium have nothing to do with this. This is related to the restricted account of the Telegram bot, which can monitor up to a maximum of 500 channels/groups. Unless the account is upgraded to extend it to 1000.

Hi,
Have the same problem. 
I did not understand your message. Can you clarify, please?
Can we do anything, or is on your side?

**Comment by Hootrix** [comment]
Due to the limitations imposed on accounts by Telegram, I highly recommend that you deploy the `keyword_alert_bot` service yourself.

https://github.com/Hootrix/keyword_alert_bot#docker
