### ISSUE TITLE
Keyword Alert Bot not responding[BUG]

### ISSUE THREAD

**Issue by everestbobby** [Hootrix/keyword_alert_bot#62]
The keyword alert bot of my telegram is not working since last week. Please fix it soon.

**Comment by Hootrix** [comment]
当前所依赖的服务器供应商遭遇了故障，暂时被下线。🤦🤦

**Comment by everestbobby** [comment]
> 当前所依赖的服务器供应商遭遇了故障，暂时被下线。🤦🤦

Can u type in English please

**Comment by cennong** [comment]
请问何时会好啊？

**Comment by Hootrix** [comment]
https://github.com/Hootrix/keyword_alert_bot/issues/63
