### ISSUE TITLE
使用这个bot后tg号开始自动退群

### ISSUE THREAD

**Issue by zoooo0** [Hootrix/keyword_alert_bot#7]
自建的话自己的群组，频道出现自动退出的情况

**Comment by Hootrix** [comment]
机器人调用的tg号最好新建一个。
内部会检测若没人订阅则退出频道，避免账户接收大量的无用消息。

> 自建的话自己的群组，频道出现自动退出的情况

**Comment by Hootrix** [comment]
> 自建的话自己的群组，频道出现自动退出的情况

文档上的确没说明，抱歉啦

> 机器人调用的tg号最好新建一个。 内部会检测若没人订阅则退出频道，避免账户接收大量的无用消息。
> 
> > 自建的话自己的群组，频道出现自动退出的情况

**Comment by tensun** [comment]
“无法使用该频道”问题 
胖大神好！keyword机器人频繁报错，原本订阅上的群组，取消-再订阅就会报错“无法使用该频道：*** Channel error, unable to use”。恳请大神修理修理！
![keyword alter bot](https://user-images.githubusercontent.com/10707563/148721662-5c5ae8e5-b20e-4f46-b684-fa16e98c0796.jpg)

**Comment by Hootrix** [comment]
> “无法使用该频道”问题 胖大神好！keyword机器人频繁报错，原本订阅上的群组，取消-再订阅就会报错“无法使用该频道：*** Channel error, unable to use”。恳请大神修理修理！ ![keyword alter bot](https://user-images.githubusercontent.com/10707563/148721662-5c5ae8e5-b20e-4f46-b684-fa16e98c0796.jpg)

看样子是账户被管理封禁，jion失败了
