### ISSUE TITLE
私密群组机器人无法工作[BUG]

### ISSUE THREAD

**Issue by yanguo0905** [Hootrix/keyword_alert_bot#70]
![image](https://github.com/Hootrix/keyword_alert_bot/assets/117158183/da3d8369-7782-41ed-b9c7-fe84f4ecc1e2)

![image](https://github.com/Hootrix/keyword_alert_bot/assets/117158183/abaab833-3371-45d6-ad0f-e529fc688f4a)
无论有没有正则表达式，私密群组始终不会被监听
![image](https://github.com/Hootrix/keyword_alert_bot/assets/117158183/fd3ac1c0-9a5d-4e96-a40e-4b4212c44507)
但是公开频道，公开群组，私密频道是正常工作的，就是私密群组不会工作，希望可以解决一下，谢谢！

**Comment by Hootrix** [comment]
ok  晚上我看下

**Comment by yanguo0905** [comment]
how is going?

**Comment by Hootrix** [comment]
电脑坏了，容我有空再看

**Comment by Hootrix** [comment]
看看有没正常

**Comment by Hootrix** [comment]
才发现私有群组以前就没支持，算是完成了一项TODO😂

**Comment by yanguo0905** [comment]
还是不行，测试了好几遍，就是私密群组不行

**Comment by yanguo0905** [comment]
您看再优化一下？

**Comment by yanguo0905** [comment]
> 才发现香蕉树以前缺乏支持，福利了一个TODO😂

还是不行，测试了好几遍，就是私密群组不行，您看再优化一下？

**Comment by yanguo0905** [comment]
> 提供下测试群链接

https://t.me/+TY_2FwHXwKs5NmYx

**Comment by crazypeace** [comment]
我的效果是这样的, 不能显示原文. 但是点击 前面的那个 "FOUND" 可以跳转到群组中的消息.
当然, 接收提醒的这个用户本身也要加入了私密群组才能跳转过去看到消息.
![image](https://github.com/Hootrix/keyword_alert_bot/assets/665889/a4913299-5a0d-4362-b9ff-90c60842730f)

源: https://github.com/crazypeace/keyword_alert_bot
