### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mohammedattm** [Hootrix/keyword_alert_bot#76]
**问题描述 Describe the bug**
请简洁明了地描述您遇到的问题。A clear and concise description of what the bug is.

**订阅信息 command Info**
请提供相关命令和信息，例如：
/subscribe 优惠券,Booked https://t.me/tianfutong

The bug is that thebot doesn't work ![Screenshot_2023-09-22-15-45-14-195-edit_org.telegram.messenger.jpg](https://github.com/Hootrix/keyword_alert_bot/assets/42580858/cd0f5432-bc92-462c-ab6c-78e21560d096)

**Comment by Hootrix** [comment]
merged into #85
