### ISSUE TITLE
相同的消息发了两遍

### ISSUE THREAD

**Issue by SherlockedTxh** [Hootrix/keyword_alert_bot#8]
/subscribe #Netflix https://t.me/hezu2
![F28E2658-13C1-4523-80B0-16C2704EB07B](https://user-images.githubusercontent.com/10359238/148529093-6a02dcc7-f59f-4482-81e4-212c87fb410c.png)

**Comment by Hootrix** [comment]
应该是短时间内触发了新建、编辑事件。有空了修复下

**Comment by fangpidedongsun** [comment]
> 应该是短时间内触发了新建、编辑事件。有空了修复下

大佬，修一下吧😂

**Comment by vmaps3** [comment]
确实是如此，订阅的英文频道里也是在短时间内发送了好几次相同的消息，希望作者大大可以抽空修复下

**Comment by jingqinglin** [comment]
![image](https://user-images.githubusercontent.com/20902987/153115666-8878ce41-5f3a-4303-bdfc-f53dcad63863.png)

**Comment by jingqinglin** [comment]
现在好像还是会有这种情况
![image](https://user-images.githubusercontent.com/20902987/153115724-721e67a9-694a-4100-a9eb-e2262a7ed5a9.png)

**Comment by Hootrix** [comment]
> 好像

我这边OK的。
是同一个频道和消息吗
把FOUND链接复制出来看下呢

**Comment by jingqinglin** [comment]
> 我这边OK的。 是同一个频道和消息吗 把FOUND链接复制出来看下呢

[这条](https://t.me/hezu2/18052)会重复发送，但同样频道里的[这条](https://t.me/hezu2/18050)就没有重复发，关键词都是 Netflix
