### ISSUE TITLE
[功能]可以过滤机器人发送的关键词？

### ISSUE THREAD

**Issue by Wu1qq** [Hootrix/keyword_alert_bot#87]
1、怎么过滤机器人发送的关键词
2、想修改一下关键词群组的提示格式如下：关键词：
                                                                       来源群组：
                                                                       发送人ID：
                                                                       发送人用户名：
                                                                       用户昵称：

**Comment by Hootrix** [comment]
目前不考虑

**Comment by Hootrix** [comment]
> 1、怎么过滤机器人发送的关键词

done

```
block_bot_msg: false # default allow
```
block_bot_msg 参数设置 为 `true`
