### ISSUE TITLE
keyword alert bot not working [BUG] in telegram 

### ISSUE THREAD

**Issue by sureshg7996** [Hootrix/keyword_alert_bot#88]
**问题描述 Describe the bug**
请简洁明了地描述您遇到的问题。A clear and concise description of what the bug is.

**订阅信息 command Info**
请提供相关命令和信息，例如：
/subscribe 优惠券,Booked https://t.me/tianfutong

**Comment by Hootrix** [comment]
具体是什么错误呢？ 接收延迟？  DEMO 的 bot 使用人数太多，我的账号限制比较严重
