### ISSUE TITLE
第21行怎么处理...

### ISSUE THREAD

**Issue by miraclemakerjoe** [Hootrix/keyword_alert_bot#90]
File "D:\Downloads\keyword_alert_bot-master\main.py", line 21, in <module>
    from utils.common import is_allow_access,banner,is_msg_block,get_event_chat_username,get_event_chat_username_list
ModuleNotFoundError: No module named 'utils.common'

**Comment by miraclemakerjoe** [comment]
这行我删掉之后暂时先试一下，
然后显示WARNING:telethon.client.users:Telegram is having internal issues AuthRestartError: Restart the authorization process (caused by SendCodeRequest)
Please enter the code you received: 48981

我要在哪里输密码？

**Comment by Hootrix** [comment]
没有测试过 Windows 的环境。可以直接用 docker

**Comment by miraclemakerjoe** [comment]
utils.common
这个要怎么装？一直找不到

**Comment by Hootrix** [comment]
> utils.common 这个要怎么装？一直找不到

https://github.com/Hootrix/keyword_alert_bot/blob/master/utils/common.py
