### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by miraclemakerjoe** [Hootrix/keyword_alert_bot#95]
请问我可以将bot加入一个家人群聊里，然后bot能在群聊里提示么？主要是我想让家人不用上我号一起得到提醒

**Comment by Hootrix** [comment]
目前不行，这个 bot 只针对单人提醒。临时解决的话可以共享监听参数  大家各自账号都会收到提醒

你主要想在群里大家共享这个 bot 的监听？  比如以群的角色来操作 bot，而不是单个用户。我空了可以研究下

**Comment by miraclemakerjoe** [comment]
> 目前不行，这个 bot 只针对单人提醒。临时解决的话可以共享监听参数 大家各自账号都会收到提醒
> 
> 你主要想在群里大家共享这个 bot 的监听？ 比如以群的角色来操作 bot，而不是单个用户。我空了可以研究下

老板我刚刚试了一下，发现是可以的，不必再劳烦了。
步骤：1.先在keybotfather那边设置 /setprivacy enable
2.把bot拉进群聊，给bot admin权限，或者至少让他能收发消息
3.回botfather那边把原先设置调回去

谢谢老板

**Comment by crazypeace** [comment]
你可以看看这个项目
https://github.com/crazypeace/tg-keyword-monitor-bot

接收命令的来源 可以是人, 也可以是群组.

发布关键字通知的对象可以是人, 也可以是群组, 也可以是频道.

https://zelikk.blogspot.com/2025/09/tg-keyword-monitor-bot-business.html
