### ISSUE TITLE
[FEATURE]表达式/(hello\s*world)(?:[^你好]|$)/ig并不能正确识别中文‘你好’，且进行排除

### ISSUE THREAD

**Issue by caco12138** [Hootrix/keyword_alert_bot#96]
也尝试过把中文换为unicode码也无法正确排除

**Comment by Hootrix** [comment]
表达式问题吧。换零宽断言`/(hello\s*world)(?!(?:.*?你\s*好))/ig`

**Comment by caco12138** [comment]
`/(hello\s*world)(?!(?:.*?你\s*好))/ig`试了试，无法排除’你好‘出现在关键词前面的情况。最后改为了`/^(?!.*你好.*hello\s*world)(.*?hello\s*world)/ig` 解决了问题，感谢
