### ISSUE TITLE
[BUG]为什么关键词获取的样式 跟你demo 的不一样？

### ISSUE THREAD

**Issue by Awhitedressy** [Hootrix/keyword_alert_bot#97]
![image](https://github.com/user-attachments/assets/ca2fab3c-4956-485f-a4db-8cb732b73c21)
![image](https://github.com/user-attachments/assets/383e9884-250b-4445-bfec-e676508c91a6)
下面这是我的。而且还没有菜单

**Comment by Hootrix** [comment]
私有频道没加入或者频道禁止转发都有可能

**Comment by Awhitedressy** [comment]
> 私有频道没加入或者频道禁止转发都有可能

那不应该菜单 也没显示出来啊

**Comment by crazypeace** [comment]
你可以看看这个项目, 针对私有群或者消息不让转发的情况, 程序会复制消息文本内容, 写在关键字提醒通知里.
https://github.com/crazypeace/tg-keyword-monitor-bot
像这样
https://t.me/FuckGFWNewbieNeedHelp

<img width="684" height="333" alt="Image" src="https://github.com/user-attachments/assets/99f86830-82e1-441f-ac57-454de57c534d" />
